### ISSUE TITLE
Question: what are the system requirements for Audiobutcher?

### ISSUE THREAD

**Issue by avachon100510** [vanpassinby/audiobutcher#1]
Pretty much what it says in the title... I want to know the necessary requirements. In addition, is there a 32-bit version as well?

**Comment by osdwa** [comment]
Well, for EXE releases, requirements are the same as for python 3.10 I think.
No, there's no 32-bit EXE release. However, AB can run on 32-bit devices, but you have to compile it yourself.

**Comment by avachon100510** [comment]
Thanks, it is very helpful. I never really needed that old Windows XP desktop anymore anyway, it was ancient. Also, how did AudioButcher start and what exactly was the inspiration behind it?

**Comment by osdwa** [comment]
Basically someone found some not-working python project for scrambling audio. Soon after, MightInvisible made their own program for randomly scrambling audio. Then other people joined the dev team (except me and f8; we joined later). And so, the program got name "Epic Music Scrambler". Later it was renamed into AudioButcher.

AB was inspired by the way how audio was scrambled in the second part of "everywhere at the end of time" album. However, AB is rather a free interpretation of it. But lately we've been trying to make it more like that hypnotic scrambler used as we know more about it.

Not sure github is for that kind of questions tho. Next time ask such questions somewhere on the discord server.
